USE [master]
GO
/****** Object:  Database [TiendaLaptopsYoutube]    Script Date: 15/07/2025 22:04:47 ******/
CREATE DATABASE [TiendaLaptopsYoutube]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TiendaLaptopsYoutube', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TiendaLaptopsYoutube.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TiendaLaptopsYoutube_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TiendaLaptopsYoutube_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TiendaLaptopsYoutube].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET ARITHABORT OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET RECOVERY FULL 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET  MULTI_USER 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TiendaLaptopsYoutube', N'ON'
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET QUERY_STORE = ON
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TiendaLaptopsYoutube]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 15/07/2025 22:04:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Laptops]    Script Date: 15/07/2025 22:04:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Laptops](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Laptops] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250715031305_TablaLaptops', N'9.0.7')
GO
SET IDENTITY_INSERT [dbo].[Laptops] ON 
GO
INSERT [dbo].[Laptops] ([Id], [Name]) VALUES (2, N'Asus 1TB SSD')
GO
INSERT [dbo].[Laptops] ([Id], [Name]) VALUES (7, N'Thoshiba 512GB SSD')
GO
INSERT [dbo].[Laptops] ([Id], [Name]) VALUES (8, N'MSI 32GB Ram 1TB SSD')
GO
SET IDENTITY_INSERT [dbo].[Laptops] OFF
GO
USE [master]
GO
ALTER DATABASE [TiendaLaptopsYoutube] SET  READ_WRITE 
GO
